# Generated by Django 4.2.5 on 2023-10-12 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_file_name_file_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='tags',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
