# Generated by Django 4.2.6 on 2023-10-31 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_artist_user_alter_artwork_artist'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotlightArt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artwork', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.artwork')),
            ],
        ),
    ]
