# Generated by Django 4.2.6 on 2023-11-01 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_filegroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_group',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='main.filegroup'),
            preserve_default=False,
        ),
    ]
