# Generated by Django 4.2.7 on 2023-11-21 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_basepage_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengePage',
            fields=[
                ('basepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.basepage')),
            ],
            options={
                'abstract': False,
            },
            bases=('main.basepage',),
        ),
        migrations.CreateModel(
            name='FoundationPage',
            fields=[
                ('basepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.basepage')),
            ],
            options={
                'abstract': False,
            },
            bases=('main.basepage',),
        ),
        migrations.CreateModel(
            name='MagazinePage',
            fields=[
                ('basepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.basepage')),
            ],
            options={
                'abstract': False,
            },
            bases=('main.basepage',),
        ),
        migrations.CreateModel(
            name='ReviewsPage',
            fields=[
                ('basepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.basepage')),
            ],
            options={
                'abstract': False,
            },
            bases=('main.basepage',),
        ),
        migrations.CreateModel(
            name='SpotlightPage',
            fields=[
                ('basepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.basepage')),
            ],
            options={
                'abstract': False,
            },
            bases=('main.basepage',),
        ),
        migrations.CreateModel(
            name='TvPage',
            fields=[
                ('basepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.basepage')),
            ],
            options={
                'abstract': False,
            },
            bases=('main.basepage',),
        ),
    ]
