# Generated by Django 4.2.7 on 2023-11-22 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_homepageslidingimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='spotlight_art',
            field=models.IntegerField(blank=True, help_text='ID of the Spotlight Art', null=True),
        ),
    ]
