# Generated by Django 4.2.7 on 2023-11-23 04:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_homepage_spotlight_art'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.FileField(upload_to=main.models.Image.save_path)),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('file_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.filegroup')),
            ],
        ),
    ]
