# Generated by Django 4.2.7 on 2023-11-23 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpotlightArt',
        ),
    ]
