# Generated by Django 4.2.7 on 2023-11-23 05:03

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_delete_spotlightart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='resource',
            field=models.ImageField(upload_to=main.models.Image.save_path),
        ),
    ]
