# Generated by Django 4.2.7 on 2023-11-23 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('main', '0017_remove_artwork_file_artwork_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='object_id',
            field=models.IntegerField(),
        ),
        migrations.AddConstraint(
            model_name='artwork',
            constraint=models.UniqueConstraint(fields=('content_type', 'object_id'), name='unique_content_object'),
        ),
    ]
