# Generated by Django 4.2.7 on 2023-11-30 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_animationchallengepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptChallengePage',
            fields=[
                ('basepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.basepage')),
            ],
            options={
                'abstract': False,
            },
            bases=('main.basepage',),
        ),
    ]
