# Generated by Django 4.2.7 on 2023-12-01 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_conceptchallengepage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='spotlight_art',
            new_name='spotlight_art_ID',
        ),
    ]
