# Generated by Django 4.2.7 on 2023-12-10 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_rename_spotlight_art_homepage_spotlight_art_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='spotlight_art_caption',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='spotlight_art_ID',
            field=models.IntegerField(blank=True, help_text='ID of the Spotlight Art (you can find it in its url)', null=True),
        ),
    ]
