# Generated by Django 4.2.7 on 2024-05-19 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_comment'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.UniqueConstraint(fields=('post_type', 'post_id'), name='unique_comment'),
        ),
    ]
