# Generated by Django 4.2.7 on 2024-05-19 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_comment_unique_comment'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='comment',
            name='unique_comment',
        ),
    ]
