# Generated by Django 5.0.6 on 2024-05-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_remove_comment_unique_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
