# Generated by Django 5.0.6 on 2024-05-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_artwork_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
