# Generated by Django 5.0.6 on 2024-05-25 15:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_alter_artwork_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='date_published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
