# Generated by Django 5.0.6 on 2024-07-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='content',
            field=models.CharField(default='', max_length=10000),
            preserve_default=False,
        ),
    ]
