# Generated by Django 5.0.6 on 2024-10-12 12:47

import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_review_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='review',
            name='genre',
            field=models.ForeignKey(default=main.models.Genre.get_default_pk, on_delete=django.db.models.deletion.CASCADE, to='main.genre'),
        ),
    ]
