# Generated by Django 5.1.2 on 2024-11-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_articlecategory_alter_review_user_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.AddField(
            model_name='article',
            name='categories',
            field=models.CharField(default='News', max_length=100),
            preserve_default=False,
        ),
    ]
