# Generated by Django 5.1.3 on 2024-11-11 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_remove_article_category_article_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='html_images',
            field=models.JSONField(default=dict),
        ),
    ]
