# Generated by Django 5.1.3 on 2024-11-14 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_article_html_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumbnail_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.image'),
        ),
    ]
