# Generated by Django 5.1.3 on 2024-11-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_productcategory_productlicense_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productxproductlicense',
            options={'verbose_name_plural': 'ProductXProductlicense'},
        ),
        migrations.AddField(
            model_name='seller',
            name='alias',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='brand_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
