# Generated by Django 5.1.3 on 2024-11-24 11:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_alter_productxproductlicense_options_seller_alias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='alias',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seller',
            name='brand_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
