# Generated by Django 5.1.3 on 2024-11-24 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_alter_seller_alias_alter_seller_brand_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='thumbnail_images',
        ),
        migrations.CreateModel(
            name='ProductXImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail_images',
            field=models.ManyToManyField(through='main.ProductXImage', to='main.image'),
        ),
    ]
