# Generated by Django 5.1.3 on 2024-11-25 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_remove_product_thumbnail_images_productximage_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FoundationPage',
            new_name='ResourcesPage',
        ),
        migrations.AlterModelOptions(
            name='productximage',
            options={'verbose_name_plural': 'Product X Image'},
        ),
        migrations.AlterModelOptions(
            name='productxproductlicense',
            options={'verbose_name_plural': 'Product X ProductLicense'},
        ),
    ]
