# Generated by Django 5.1.3 on 2024-11-25 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_rename_foundationpage_resourcespage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='sub_categories',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
