# Generated by Django 5.1.3 on 2024-11-25 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_productcategory_sub_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='sub_categories',
        ),
        migrations.AddField(
            model_name='productcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.productcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.productcategory'),
        ),
    ]
