# Generated by Django 5.1.3 on 2024-12-02 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_alter_productcategory_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='slug',
            new_name='path',
        ),
    ]
