# Generated by Django 5.1.3 on 2024-12-02 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_rename_slug_productcategory_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='path',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
