# Generated by Django 5.1.3 on 2024-12-10 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_alter_productcategory_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productrating',
            old_name='user_rating',
            new_name='stars',
        ),
    ]
