# Generated by Django 5.1.3 on 2024-12-10 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_rename_user_rating_productrating_stars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user_ratings',
        ),
        migrations.AddField(
            model_name='productrating',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='main.product'),
            preserve_default=False,
        ),
    ]
