# Generated by Django 5.1.3 on 2024-12-26 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_alter_productcategory_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductLicense',
            new_name='License',
        ),
        migrations.RemoveField(
            model_name='product',
            name='licenses',
        ),
        migrations.DeleteModel(
            name='ProductXProductlicense',
        ),
    ]
