# Generated by Django 5.1.3 on 2024-12-26 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_rename_productlicense_license_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.file')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductItemXLicence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.license')),
                ('product_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.productitem')),
            ],
            options={
                'verbose_name_plural': 'ProductItem X File',
            },
        ),
        migrations.AddField(
            model_name='productitem',
            name='licence',
            field=models.ManyToManyField(through='main.ProductItemXLicence', to='main.license'),
        ),
    ]
