# Generated by Django 5.1.3 on 2024-12-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_productitem_productitemxlicence_productitem_licence'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductItemXLicence',
            new_name='ProductItemXLicense',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='licence',
        ),
        migrations.AddField(
            model_name='productitem',
            name='license',
            field=models.ManyToManyField(through='main.ProductItemXLicense', to='main.license'),
        ),
    ]
