# Generated by Django 5.1.3 on 2024-12-27 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0062_rename_productitemxlicence_productitemxlicense_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productitemxlicense',
            options={'verbose_name_plural': 'ProductItem X License'},
        ),
    ]
