# Generated by Django 5.1.3 on 2024-12-27 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0063_alter_productitemxlicense_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productitem',
            old_name='license',
            new_name='licenses',
        ),
    ]
