# Generated by Django 5.1.3 on 2024-12-31 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0065_remove_product_price_productxlicense_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='path',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
