# Generated by Django 5.1.4 on 2025-01-30 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0066_alter_productcategory_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='free',
            field=models.BooleanField(default=False),
        ),
    ]
