# Generated by Django 5.1.4 on 2025-02-24 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0067_license_free'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='file',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.file'),
        ),
    ]
