# Generated by Django 5.1.4 on 2025-03-11 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0069_contest_contestentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contestentry',
            options={'verbose_name_plural': 'Entries'},
        ),
    ]
