# Generated by Django 5.1.4 on 2025-03-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0070_alter_contestentry_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestentry',
            name='mention',
            field=models.BooleanField(default=False),
        ),
    ]
