# Generated by Django 5.1.4 on 2025-03-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0071_contestentry_mention'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contestentry',
            options={'verbose_name_plural': 'Contest Entries'},
        ),
        migrations.AddField(
            model_name='product',
            name='listed',
            field=models.BooleanField(default=True),
        ),
    ]
