# Generated by Django 5.1.4 on 2025-04-02 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0072_alter_contestentry_options_product_listed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_library', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Product Libraries',
            },
        ),
        migrations.CreateModel(
            name='ProductLibraryXXProductXLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.productlibrary')),
                ('productxlicense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.productxlicense')),
            ],
            options={
                'verbose_name_plural': 'ProductLibrary XX ProductXLicense',
            },
        ),
        migrations.AddField(
            model_name='productlibrary',
            name='productxlicenses',
            field=models.ManyToManyField(through='main.ProductLibraryXXProductXLicense', to='main.productxlicense'),
        ),
    ]
