# Generated by Django 5.1.4 on 2025-04-05 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0073_productlibrary_productlibraryxxproductxlicense_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetupPage',
            fields=[
                ('basepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.basepage')),
            ],
            options={
                'abstract': False,
            },
            bases=('main.basepage',),
        ),
    ]
