# Generated by Django 5.1.4 on 2025-04-05 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0074_meetuppage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MeetupPage',
            new_name='MeetupsPage',
        ),
    ]
