# Generated by Django 5.1.4 on 2025-11-09 20:40

import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0075_rename_meetuppage_meetupspage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtworkVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.SmallIntegerField()),
                ('image', models.ImageField(upload_to=main.models.ArtworkVariant.save_path)),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.artwork')),
            ],
        ),
    ]
