# Generated by Django 4.2.5 on 2023-09-29 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, default='nulluser', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
