# Generated by Django 4.2.6 on 2023-10-21 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_is_verified_alter_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='image_file',
            new_name='profile_image',
        ),
    ]
