# Generated by Django 5.0.6 on 2024-08-12 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_user_is_reviewer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_reviewer',
        ),
    ]
