# Generated by Django 5.0.6 on 2024-10-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_remove_user_is_reviewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(default='Nothing written in bio.', max_length=500),
        ),
    ]
