# Generated by Django 5.1.3 on 2024-12-15 15:00

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.User.profile_pic_save_path),
        ),
    ]
